### PR TITLE
BATTERY THRESHOLD PERCENT

### PR DESCRIPTION
**Pull request by albertsal**
I added the option to set the battery threshold by tapping the battery
icon, I made sure each device has its own threshold

HPLUS: I put a small correction to show the low battery notification

### CODE REVIEW

**Comment by jpbarraca** [comment]
I would prefer this to be in the HPlus settings panel.
The objective is to keep all settings in the same place instead of scattering configuration points across the app.

**Comment by albertsal** [comment]
Initially I did this, but I noticed that each device can have a different threshold. For example i have 2 devices the first device should be set between 15% and 20% because below this threshold goes off, for the second device it is ok 10%

**Comment by jpbarraca** [comment]
Ideally we would have completely different settings for different devices.
@cpfeiffer : how is this handled with Mi Band and Pebble?

**Comment by albertsal** [comment]
I have 2 device for hplus ... zeband and s200

**Comment by cpfeiffer** [comment]
Mi Bands provide the battery level on request. Additionally they notify low battery state on their own. I think we have a hardcoded threshold somewhere that colours the displayed battery level in red.

For Pebble, the whole battery handling is WIP, AFAIK.

IMHO this need not be user configurable. We could hardcode device specific thresholds though (need feedback on the different devices though, maybe with a wiki page?)

**Comment by albertsal** [comment]
@cpfeiffer ok is clear... so it is possible that some devices HPlus do not have  notification ... @jpbarraca your devices have notified?

**Comment by cpfeiffer** [comment]
@albertsal Yes, that's certainly possible. I do not have any HPlus device yet, so I can't say if *any* HPlus device provide battery notifications.

**Comment by albertsal** [comment]
@cpfeiffer  Ok i could just put a single global setting for all devices or put it on hplus only ... but if you think we'll soon think of this change we can close the pr

**Pull request closed without merging**
