### PR TITLE
Adding Lithuanian transliteration

### PR DESCRIPTION
**Pull request by UncleInf**
Added Lithuanian language transliteration.

### CODE REVIEW

**Comment by TaaviE** [comment]
Just mentioning, there's a fairly nice webGUI for translations at https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/ you can use for further edits.

**Comment by UncleInf** [comment]
Thank you for info, I will try to contribute some translations there too. This commit is for Lithuanian chars transliteration to ascii variant.

**Comment by cpfeiffer** [comment]
Thanks a lot! :smile:

**Comment by cpfeiffer** [comment]
@TaaviE I also misread this as "translation" first, but this is about *transliteration*.

**Pull request merged**
