### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by TaaviE**
First step towards migrating to Gradle 3.0 properly, changed all `compile`s to `implementation`s. Tests show only marginally faster compilation and no ill effects. https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

Changed all `'` to `"` for consistency.

Also made a few whitespace and capitalization changes and removed an unnecessary `;`

### CODE REVIEW

**Comment by TaaviE** [comment]
It's also worth noting that there's a newer version of Android support libraries available `27.1.0`.

**Comment by danielegobbetti** [comment]
Thanks, I will check other apps in the fdroid metadata repo to be sure gradle 3 is supported by them.

**Comment by danielegobbetti** [comment]
Yeah sorry I miswrote, I meant checking for other apps using the new syntax.

**Comment by danielegobbetti** [comment]
At least conversations is already using the new syntax, hence +1 from me. (To be complete, they are using single quotes but I can't imagine that creating problems).

**Pull request merged**
