### PR TITLE
Watch 9: Initial support

### PR DESCRIPTION
**Pull request by maxirnilian**
Initial support for Watch 9 (hybrid smartwatch)

Working: 
- Notifications
- Alarms (maybe some further testing is needed to verify every alarm scenario)
- Setting step goal (progress can be checked on the watch face)
- Time calibration/sync

Some features are missing, but for now that is everything I found out.

### CODE REVIEW

**Comment by maxirnilian** [comment]
Hey, thanks for the quick review. Do I just have to commit the necessary changes to my branch to appear here for a re-review (this PR stuff is pretty new to me :see_no_evil:)?

The Watch is related to issue #1156 (Lenovo Watch 9), sorry missed that in the first comment. I didn't find more useful (or any official) device related stuff than those links in the issue. I would guess that there are more devices using the underlying hardware, but can't say that for sure. 

Sounds good, I can not add much more for now. What do you think would be the best practice? Maybe someone else owning this device would like to take a look on the missing features and/or improvements, so is it ok to have it on master or would it be better in a separate branch?

One additional question, GB seems to be "unable" to handle battery info correctly for devices having a battery state (OK or LOW) but not a battery level (always fires low battery -1% notification) should I open a separate issue for that or just change it so you can also review this here?

**Comment by cpfeiffer** [comment]
I'm fine with merging this early. Now we even have an independent confirmation by @f3z that it works, so that's great!

After it's merged, just create new pull requests for further changes.

For the battery problem, please open a new issue. I don't quite understand if the problem is in BLE code or in the UI side or somewhere else, so let's discuss this in a separate issue.

**Comment by cpfeiffer** [comment]
So I'm merging this. Thanks a bunch :tada:

**Comment by maxirnilian** [comment]
Oh that was fast, I haven't even managed to apply your remarks yet. Maybe those can be merged at a later point, since the changes seem to be quiet small.

> So I'm merging this. Thanks a bunch :tada: 

No probs, I'm happy I could spend support to this project.

> For the battery problem, please open a new issue. 

OK, will do :+1:

**Comment by cpfeiffer** [comment]
Right, the few changes can be quickly applied when you submit them.

**Pull request merged**
