### PR TITLE
Support for button actions on Mi Band 2 device

### PR DESCRIPTION
**Pull request by MigNov**
Hi,
I'm opening a pull request because this is what I find very useful for programming purposes. Some time ago I developer an app that's catching the official Mi Fit app & Notify App for Mi Band 2 broadcast intent called the "Tasker action". I was googling and found your brilliant Gadgetbridge app so I decided to implement the functionality I've been using from the original app. This is pretty useful for anybody needing to send broadcast to any app so they can hook on the Mi Band's button and do their own stuff.

Hopefully it will be found useful for others as well.

Thanks,
Michal

### CODE REVIEW

**Comment by MigNov** [comment]
Hopefully you'll find it useful as well. I've tried in on Samsung with Android 5.0.2 and also Elephone P9000 with Android 6.0 and it was working like a charm :-)

For any question and feedback feel free to ask me :+1: 
Michal (a.k.a. Mig)

**Comment by cpfeiffer** [comment]
Thanks a bunch! :-)

**Comment by MigNov** [comment]
Thanks for merging :-) If I think about anything else interesting for the Gadgetbridge I'll try to develop and once done I'll open a new pull request again :-)

Thanks again!
Michal

**Comment by cpfeiffer** [comment]
Great, looking forward to that! :+1:

**Pull request merged**
