### PR TITLE
Pebble: add support for weather in Simply Light watchface

### PR DESCRIPTION
**Pull request by slp**
Celsius forced as with other watchfaces #482

### CODE REVIEW

**Comment by danielegobbetti** [comment]
Nice! Thanks for the contribution.

I was wondering whether there is a key to make sure the watchface knows the temperature is in Celsius (see for instance [this line](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerTimeStylePebble.java#L140) )

**Comment by slp** [comment]
@danielegobbetti 

> I was wondering whether there is a key to make sure the watchface knows the temperature is in Celsius (see for instance this line )

The conversion is done in the JS part:

simply-light/src/js/app.js:
`
258             var units = WeatherMan.KELVIN;
259             if (config.configuration.temperature_units == 'imperial') {
260                 units = WeatherMan.FAHRENHEIT;
261             }
262             else if (config.configuration.temperature_units == 'metric') {
263                 units = WeatherMan.CELCIUS;
264             }
265 
`
Unless there's a way we can read the configuration from Gadgetbridge and do the conversion beforehand, I don't it'd be possible to support choosing between units.

**Comment by danielegobbetti** [comment]
Unrelated: does the watch face work with background js enabled?

**Comment by slp** [comment]
> Unrelated: does the watch face work with background js enabled?

Nope. The problem appears to be related to some TypeErrors that start appearing after enabling background js. There are also some issues trying to generate the configuration data for the watchface. TBH, I haven't paid much attention to any of these issues.

**Comment by danielegobbetti** [comment]
@slp can you please test if the errors are still there also in latest master? In our JSON message the metadata part was completely missing until latest commit.
Is the watchface open source? I would like to test it with background JS enabled.

I have no objections in merging this PR, but I would like @ashimokawa to give a second look. Anyway, +1 from here! 

Thanks again!

**Comment by ashimokawa** [comment]
@slp 
Looks good to me. :+1: 

HOWEVER :stuck_out_tongue: 

We originally planned to remove all these handlers when background javascript works, but since that seems to be so complicated and you did the work already, I will still merge it. :wink:

**Comment by IzzySoft** [comment]
@ashimokawa 

> We originally planned to remove all these handlers when background javascript works

… and does not consume twice as much battery. Still have this issue here. Additionally to the log I've sent you: I've noticed multiple reboots of my Pebble over the day, usually when some notification is received. Not on every notification, so I cannot reproduce it at-will …

Switching off BGJS, and those issues are not there.

Sorry for abusing this issue – but I jumped on "when BGJS works" :wink:

**Comment by slp** [comment]
> @slp can you please test if the errors are still there also in latest master? In our JSON message the metadata part was completely missing until latest commit.
> Is the watchface open source? I would like to test it with background JS enabled.

@danielegobbetti Just gave it a try. It no longer complains about the missing transactionId, but the weather is still not showing up. I haven't looked further into this.

This watchface is GPLv3:

https://github.com/bhdouglass/simply-light

**Comment by slp** [comment]
@ashimokawa 

> We originally planned to remove all these handlers when background javascript works, but since that seems to be so complicated and you did the work already, I will still merge it.

Thanks!

As @IzzySoft already commented, if it's not much of maintenance burden, having the option to use the handlers instead of the background JS would be a really nice option. IMHO, this is just another advantage of Gadgetbridge over the stock Pebble app.

**Comment by danielegobbetti** [comment]
@slp the issue with the handlers is that the key IDs (potentially) change with version upgrades, which makes the whole process very fragile.

Before you ask: yes, that happened already with Timestyle, we updated the handler but of course doing so we fixed the new version by breaking the old one...

**Comment by slp** [comment]
@danielegobbetti Yikes. On the other hand, is not possible to register the same handler with two different uuids? Just curious, I know that doesn't help with the maintenance burden.

**Comment by danielegobbetti** [comment]
> On the other hand, is not possible to register the same handler with two different uuids?
Indeed it is possible, see for instance the ``UUID_ZALEWSZCZAK_*`` UUIDS, all handled by the same handler.

**Comment by czandor** [comment]
Hello,

I want to make my watchface NineTime compatible with gadgetbridge. Now, the new unpublished version is working well, except the wind speed in current weather, and there is no forecast weather.
Please add wind direction and speed to mimicOpenWeatherMapResponse, and I need the forecast if possible.

**Comment by IzzySoft** [comment]
@czandor see [here](https://github.com/Freeyourgadget/Gadgetbridge/issues/482#issuecomment-373929855) (same request from another watchface dev).

**Pull request merged**
