### PR TITLE
Label piechart

### PR DESCRIPTION
**Pull request by albertsal**
small fix that removes pies labels.
I noticed that the labels have a white font and you can see if it moves
the graph

### CODE REVIEW

**Comment by cpfeiffer** [comment]
I don't quite understand -- do you have a screenshot of what's wrong?

**Comment by albertsal** [comment]
image

I changed a bit the contrast so you can see better the problem

**Comment by cpfeiffer** [comment]
That's how it looks with your patch, but what was wrong with showing the label?

**Comment by danielegobbetti** [comment]
On the light theme the first line "Xh YYmin" is visible, the second line "Light sleep"/"Deep sleep" is white on white.

**Comment by danielegobbetti** [comment]
@albertsal your PR pointed me in the right direction to catch the bug, but I fixed it by showing the labels also on the light theme instead of hiding it :-)

**Comment by albertsal** [comment]
Yes @danielegobbetti the label is white and background is white.
But you rotate the chart the label go on  background blu of the chart and read partial label...

I think it is not necessary that label if the legend down there

**Comment by albertsal** [comment]
Ok @danielegobbetti I read just now your last post

**Pull request closed without merging**
