### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by Bozydarek**
Add some new translations and fix some typos.

### CODE REVIEW

**Comment by ashimokawa** [comment]
It seems you made exactly the same changes via weblate and I already pulled from there, can we close this?

**Comment by Bozydarek** [comment]
Sure :)

**Comment by ashimokawa** [comment]
ok ;)
Before releasing I will pull weblate again, so no need for a PR if you use weblate anyway.

**Comment by Bozydarek** [comment]
Good to know. Thanks

**Pull request closed without merging**
