### PR TITLE
Speed zones tab

### PR DESCRIPTION
**Pull request by Vebryn**
Hi,

I split my pull requests into this one and another one concerning csv export. There is my master branch and this speed-zones branch. Any advices on pull request / commit / branch management are welcome :)

I simplified speed zones tab by displaying raw data instead of calculated and analyzed data.

Best regards.

### CODE REVIEW

**Comment by Vebryn** [comment]
Any advice ? Great to see GB here again :+1:

**Comment by ashimokawa** [comment]
@Vebryn 

Sorry for coming back to you so late.

Actually both of your PRs contain a lot of random unrelated commits and are really hard to understand that way. If you click on "Files Changed" above, you will see what I mean.

You are probably not aware that if you do a PR and then push changes to your branch, the commit are added to the PR. In other words, you CANNOT have two PRs on one branch in your repository.

Best thing to do is to have one branch per feature in your repository and do a PR for each of them. Then when we discuss your changes you can fix things on the corresponding branch and the added commits will be incuded in the correct PR automatically and you don't have to do another one.

**Comment by Vebryn** [comment]
Thanks, indeed I notice too late that my commits were all together. Is closing current branch and opening 2 dedicated ones the best solution ?

**Comment by Vebryn** [comment]
PR closed, I'm going to open a new one into a dedicated branch.

**Pull request closed without merging**
