### PR TITLE
Font size bar chart

### PR DESCRIPTION
**Pull request by albertsal**
small fix that improves the readability of the values on bar charts

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Hardcoding BLACK makes it pretty much unreadable in the dark theme. @danielegobbetti is working on the styles, so maybe we will get properly styled charts at some point. At the moment, the hardcoded GRAY works for both themes.

Changing the font size is OK though.

**Comment by albertsal** [comment]
ok tk

**Comment by cpfeiffer** [comment]
Thanks, Alberto!

**Comment by albertsal** [comment]
;)

**Pull request merged**
