### PR TITLE
That's the same person

### PR DESCRIPTION
**Pull request by Almtesh**
"Gilles MOREL <contact@gilles-morel.fr>" and "Gilles Émilien MOREL <Almtesh@users.noreply.github.com>" are both me.

### CODE REVIEW

**Comment by danielegobbetti** [comment]
Can you please add a gist under your github user (https://github.com/Almtesh) with the same statement? (If you can think of other ways to verify your claim, please do tell that's just my first idea). I will then change the mail mapping of the contributors script.

**Comment by danielegobbetti** [comment]
You are right that the gist part could possibly be skipped. I sent an email to the ``@gilles-morel.fr`` address to ask for confirmation. Thanks!

**Comment by Almtesh** [comment]
@danielegobbetti, I was trying a new e-mail server configuration at this moment, your e-mail server recieved a permanent error because the new config was not readable by my server.
Can you send again your e-mail?

**Comment by Almtesh** [comment]
@danielegobbetti I finally used weblate. pearhaps there will be another me in the list is the identification does not match…

**Comment by danielegobbetti** [comment]
updated script pushed to master with your contacts info merged. Please followup if there's something wrong.

**Pull request closed without merging**
