### PR TITLE
Add Set Activity Fetch Time to debug to set lastSyncTimeMillis

### PR DESCRIPTION
**Pull request by vanous**
This allows to go back in time to re-fetch data if needed.
I auto re-formatted the DebugActivity file. Generally, i try not to do this but i left it this time, please tell me if this is not good.

### CODE REVIEW

**Comment by ashimokawa** [comment]
@vanous 
Will test, I had problems with the layout on small devices. So I am cautious.

**Comment by vanous** [comment]
I see. What is the best way for me, setup emulator with smaller resolution /screen? Do you remember the size?

**Comment by ashimokawa** [comment]
You dont need the emulator, you can use the preview in android studio and change the emulated

**Comment by vanous** [comment]
OK. Seems OK here, tried bunch (probably pretty much all sub 5") of devices from Generic Phones.

**Comment by ashimokawa** [comment]
rebased and merged, thanks!

**Pull request closed without merging**
