### PR TITLE
Extract music shuffle and repeat states and set the song progress to auto-update.

### PR DESCRIPTION
**Pull request by Avamander**
I don't see it used anywhere, but it might be useful to have that data too. Though as Pebbles do nothing with the data I can't verify it being 100% correct. (Squash merge is recommended again as it would keep the history cleaner)

### CODE REVIEW

**Comment by Avamander** [comment]
Though I still lack the knowledge to make the progress bar smoothly update. It would be really lovely if someone pointed me in the right direction.

**Comment by Avamander** [comment]
Okay, I made a small Timer to update the seconds continuously. I did what I could.

**Comment by ashimokawa** [comment]
@Avamander 
I dont understand why you update the progress. The pebble does this automatically.

**Comment by Avamander** [comment]
I'm using Android 4.4 and most certainly the progress is not updated.

**Comment by ashimokawa** [comment]
@Avamander
As long as the pebble knows the song is playing it progresses automatically, has nothing to do with the Android version.

**Comment by Avamander** [comment]
Well the progress bar on my Pebble Time says otherwise. It's literally not updating unless a media intent is received.

**Comment by ashimokawa** [comment]
@Avamander 
Then I am 100% sure the pebble is not in "playing" state in your case - it does update when it is playing. On the Pebble Time.

**Comment by Avamander** [comment]
@ashimokawa What state can it be in if it doesn't show the "pause" icon and it easily switches between playing and not playing icons? It's playing, the Pebble knows it, I know it, the app knows it but the progress is not updating. See https://github.com/Freeyourgadget/Gadgetbridge/issues/536

**Comment by ashimokawa** [comment]
@Avamander 
Do other players work? Trust me if everything is done correctly from Gadgetbridge the pebble music app would update the position automatically. There has to another problem.

**Comment by Avamander** [comment]
I also tried Google Play Music, using the latest master without my continuous update code, no it does not update the position automatically. As far as I understood danielegobbetti it's a known problem.

Though I think I found a bug with seeking while paused, need to fix that.

**Comment by danielegobbetti** [comment]
I'm from mobile and didn't check neither original code nor the PR, but perhaps a missing/wrong playing rate could be the culprit?

**Comment by Avamander** [comment]
If that is the case I'll just set the right play speed and remove the unnecessary code.

**Comment by Avamander** [comment]
Did that and it should be fine now. Thanks for the information about playRate.

**Comment by ashimokawa** [comment]
@Avamander

Please remove all formatting changes in MusicStateSpec.java

**Comment by ashimokawa** [comment]
@Avamander 
Thanks!

**Comment by Avamander** [comment]
Always happy to help.

**Pull request merged**
