### PR TITLE
Refresh control center on menu change

### PR DESCRIPTION
**Pull request by vanous**
Sorry for these small changes, i will try to get better in the future.

### CODE REVIEW

**Comment by ashimokawa** [comment]
@vanous 
What does this fix?
Is it necessary to recreate the whole Activity?

**Comment by vanous** [comment]
The fob doesn't get drawn, if it was enabled after being previously disabled. Can I redraw/recreate just the fob?

**Comment by ashimokawa** [comment]
@vanous 
Yes, move the fab local variable to a private class member variable then just call fab.show()/fab.hide()

**Comment by vanous** [comment]
Thank you very much, i will look into it.

**Comment by ashimokawa** [comment]
rebased, squashed and merged - will do some further changes

**Pull request closed without merging**
