### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by giupardeb**
Fix UX string visualitazion

### CODE REVIEW

**Comment by giupardeb** [comment]
Maybe travis doesn't work. I edited only one string on strings.xml Why failed it?

**Comment by IzzySoft** [comment]
@giupardeb if you click the "Details" link, you can find out:

~~~
/home/travis/.travis/functions: line 104: sdkmanager: command not found
The command "yes | sdkmanager "platforms;android-28"" failed and exited with 127 during .
~~~

So not your fault, I'd say – looks to me like it would fail for everything at the moment as it cannot find the `sdkmanager` executable.

**Comment by giupardeb** [comment]
Ok I understand..I had not seen the "Details" button xD

**Comment by IzzySoft** [comment]
I cannot tell, I'm not a dev. Just a happy GB user 😃

**Comment by ashimokawa** [comment]
Travis sucks, useless crap.

**Comment by IzzySoft** [comment]
If *you* say so: Kick it, you've got the power :rofl:

**Comment by ashimokawa** [comment]
PRs to fix Travis will be accepted but it really sucks that it needs so much work even if we do not change anything.

**Comment by ashimokawa** [comment]
@giupardeb 
What is the idea about this PR?
Why is HR better than heart rate sensor?

**Comment by giupardeb** [comment]
@ashimokawa 
To avoid this UX bug:
photo_2019-07-27_09-47-47
it's very unsightly

**Pull request closed without merging**
