### PR TITLE
NO.1 F1: Display settings.

### PR DESCRIPTION
**Pull request by protomors**
Measurement system for distance uses new global setting. And time format is set according to Android settings (the same implementation as for MiBand).

But I have a question. I have to reconnect to band for settings to take effect because they are sent during initialization. Is this just Gadgetbridge limitation? Or do I need to implement something for settings to be sent immediatly?

### CODE REVIEW

**Comment by ashimokawa** [comment]
You can have a look at

https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java

There configuration changes will be sent to the device immediately.
We need something like this for the general configuration activity (I can prepare this today)

You would then have to implement onSendConfiguration() in your devicesupport class (look at MiBand2Support.java)

**Comment by protomors** [comment]
Thank you. I looked into code for MiBand but didn't notice this method. Soon I will add it to this pull request.

**Comment by ashimokawa** [comment]
@protomors 
Just pushed 6d8ffad55cecc1da3fd6bc9a04d60605070260cd , you can now implement onSendConfiguration in a similar fashion

**Comment by ashimokawa** [comment]
I would like to release today at 23:00 CEST since the Mi2/Bip sleep fixes are important, shall I merge this as is before if there are no changes to this PR?

**Comment by protomors** [comment]
I made changes to the pull request. Now it can be merged.

**Comment by ashimokawa** [comment]
Thanks ;) - Will merge when i am at home

**Pull request merged**
