### PR TITLE
add device Support for Denver BFH-16

### PR DESCRIPTION
**Pull request by Sophanimus**
Added basic BFH-16 device support

**working functions:**
- send notification message
- send call notification
- set alarm (1-3)
- find device
- switch automated heartbeat detection
- get firmware version
- get battery level

- get steps
- get heart rate
- get blood preasure
- get blood satiation

Communication protocol of BFH-16 is related to JYOU protocol

[DENVER BFH-16 Manufacturer Website](https://denver-electronics.com/products/wearable-and-smart-fitness/denver-bfh-16/c-1024/c-1110/p-3342)
[BFH-16 GooglePlay App](https://play.google.com/store/apps/details?id=com.janyun.bfh&hl=gsw)

### CODE REVIEW

**Comment by ashimokawa** [comment]
Cool, will merge this soon, sorry for the delay!

**Comment by ashimokawa** [comment]
@Sophanimus 
Do you think it is the same protocol as JYOU? Or at least similar enough to merge code with the Teclast H30 code already there? Or shall we keep this idependet?

**Comment by Sophanimus** [comment]
@ashimokaw
The protocol is mostly the same as used by the Teclast H30, but in some parts different (for example RECEIVE_HEARTRATE byte is 0xE8 instead of 0xFC). I think its possible to reuse some functions for both devices, but for to moment i would prefer to keep it independen. Nevertheless the BFH-16 device should be grouped with Teclast in the JYOU "group".

**Comment by ashimokawa** [comment]
@Sophanimus 
Thanks!

Your commits are now in master, but somehow github did not notice, and I had to close this manually. Maybe you should delete your fork and create a new one, so that we do not run into conflilcts when you do a new PR.

**Pull request closed without merging**
