### PR TITLE
WIP: New Device: Fossil Q Hybrid / Skagen Connected

### PR DESCRIPTION
**Pull request by dakhnod**
This work in Progress Branch integrates the above mentioned devices.

The App allows to show notification on the watch, as well as programming the buttons on the watch to trigger an Intent Broadcast that can be caught e.g. by Tasker and further linked to actions.

I have yet to clean up the code, remove the Tasker integration, and somehow get rid of my [getDeviceSupport](https://github.com/Freeyourgadget/Gadgetbridge/compare/master...dakhnod:fossil-q-hybrid#diff-8f85c8dca73667203ed424ba414dfbb3R817) implementation.

### CODE REVIEW

**Comment by ashimokawa** [comment]
Cool, new device support is always welcome :+1:

**Comment by dakhnod** [comment]
@ashimokawa  I have been working on this for nearly a year now, but need to do some work in order to include different Q and Skagen models

**Comment by ashimokawa** [comment]
@dakhnod 
Is app/libs/qbase.jar still required? If this is copyrighted original code we cannot merge this...

**Comment by dakhnod** [comment]
@ashimokawa No, it is not required...just forgot to clean it up yet...

**Comment by ashimokawa** [comment]
@ashimokawa 
can you rebase your branch and remove the commit where the jar was added, then force-push to your branch?

The reason is that it is better if the .jar is not part of Gadgetbridge's history.
Unfortunately if we would migrate to codeberg.org now this PR would become a branch automatically (even when open or closed).
So please do not close this.

**Comment by dakhnod** [comment]
could i delete and reopen the whole branch?

**Comment by ashimokawa** [comment]
Yes, should work

**Comment by dakhnod** [comment]
closing due to vendor-specific code

**Pull request closed without merging**
