### PR TITLE
German Fix

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by ashimokawa** [comment]
Would you mind using weblate for translations?

https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/

If not I can merge that manually this time

**Comment by Henry2o1o** [comment]
I have not known and used this yet. I can test it.

**Comment by Henry2o1o** [comment]
Translation in the "she" or "you" form?

**Comment by Henry2o1o** [comment]
Hello, I added everything to "weblate" and checked and edited every string again.
So do **NOT** take it from the Github!

**Comment by ashimokawa** [comment]
Ok I merged it.
There are a few questionable translations though:

-  <string name="pref_title_call_privacy_mode">Privatsphäre-Modus für Anrufe</string>
+  <string name="pref_title_call_privacy_mode">Datenschutzmodus aufrufen</string>

Actually this *is* for Calls = für Telefonanrufe

**Pull request closed without merging**
