### PR TITLE
Transliterate unsupported Russian characters into English

### PR DESCRIPTION
**Pull request by ivanovlev**
Zeblaze ZeBand don't support russian language, so i found the great solution. Just transliterated to eng unsupported chars. Other symbols are not affected.

Method can be extended for other languages, it's very easy.

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Cool, thanks for the fix and congratulations for getting Issue #500 :-)

Would you mind moving the transliteration functionality into a separate class, e.g. LanguageUtils in the utils package? Then we can easily reuse it for other devices with similar problems.

And we can spare the additional guava dependency by using Collections.unmodifiableMap() instead.

**Comment by jpbarraca** [comment]
Very nice. I have the same problem with Portuguese.

**Comment by ashimokawa** [comment]
Are ä,ö,ü and ß also unsupported?

**Comment by jpbarraca** [comment]
Actually, the band displays the ASCII table correctly with some messages, but with the current code, accented letters do not work. I have problems with á õ ã à é í ó ç â ê and so on.

**Comment by ivanovlev** [comment]
cpfeiffer, ok

**Comment by ivanovlev** [comment]
jpbarraca, afformative, after 175 just china letters. Bitches

but á õ ã à é í ç â ê still present, except ó. I'm working under specific overrides  by ascii codes for standard transliterations...

**Comment by ivanovlev** [comment]
Now orčpžsíáýd will be conveted into orcpzsiayd

**Comment by jpbarraca** [comment]
The band expects messages to be in GB2312.

**Comment by ashimokawa** [comment]
@jpbarraca 
But no complete charset I guess, so still no cyrillic?

http://www.herongyang.com/gb2312/GB2312-to-Unicode-Row-07-Cyrillic-Character.html

**Comment by jpbarraca** [comment]
It seems that the charset is limited to 8 bits.

**Comment by cpfeiffer** [comment]
Did you have a look at http://www.herongyang.com/gb2312/GB2312Unicode-Java-GB2312-Unicode-Mapping.html ?
Among others, it says
> // GB2312 is not supported by JDK. So I am using GBK.

So with the encoding class given above, we could properly encode the strings instead of just casting char to byte. (See String.getBytes(Charset))

**Comment by jpbarraca** [comment]
Had no luck with characters above 175. Even when sending specific byte sequences using a dedicated python script. The original app also has problems with accented characters.

This lets me believe that the charset is limited.

**Comment by ashimokawa** [comment]
@jpbarraca 

Couldn't you reproduce what @ivanovlev said? I mean Chinese characters above 175.
If there are Chinese characters, it seems unlikely to me that it is an 8-bit encoding. If it is still an 8-bit encoding, the chinese characters could be only the ones used for time and date like 月火水木金土日年. Unfortunately, lacking the device, I cannot test..

**Comment by ivanovlev** [comment]
If i modify debug screen command "Send" for codes "String.valueOf(Character.toChars(int))", the device can correctly show chars under to 175, 176 return black, 177+ returns china letters. ~250 again returns black, after 255 table repeats (a,b,c...)

**Comment by cpfeiffer** [comment]
So what's the current status of this PR -- should we merge it or are you still working on the details of encoding?

**Comment by ivanovlev** [comment]
Yes you can merge, i thought about extended russian transliteration (set different replacement current character by previous character), but I will not do it. Method becomes a to closed relative the other languages.

**Comment by cpfeiffer** [comment]
Thanks :-)

**Comment by ivanovlev** [comment]
@cpfeiffer Can you change one missing thing - Debug > "Send notification". I just seen, that debug "Send" button doesn't use DeviceCommunicationService, so the transliteration does not apply.

`String testString = editContent.getText().toString();`

to

`String testString = editContent.getText().toString();

if(LanguageUtils.transliterate())
{
        testString = LanguageUtils.transliterate(testString);
}
`

**Comment by ivanovlev** [comment]
@cpfeiffer Can you change one missing thing - Debug > "Send notification". I just seen, that debug "Send" button doesn't use DeviceCommunicationService, so the transliteration does not apply.

DebugActivity.java

add simple method

` // Return user input from screen`
`    private String GetUserMessage()`
`    {`
`        String message = editContent.getText().toString();`
`        if (LanguageUtils.transliterate())`
`        {`
`            return LanguageUtils.transliterate(message);`
`        }`

`        return message;`
`    }`

and replace all usage of

`String testString = editContent.getText().toString();`

to `GetUserMessage()`

**Pull request merged**
