### PR TITLE
Add miband bluetooth codes for fw 5.15.8.21

### PR DESCRIPTION
**Pull request by platinumthinker**
I sniff my mi band (v.1.1 with white LED) and add new codes.

### CODE REVIEW

**Comment by platinumthinker** [comment]
PS: I use BLExplorer from my phone.

**Comment by cpfeiffer** [comment]
Thanks -- I don't want to merge this as is, as I'd like to mark the additional characteristics as for this fw only. If you add the comments yourself, I'll merge it, otherwise I'll do it later.

**Comment by platinumthinker** [comment]
I am in the process of further details

**Comment by danielegobbetti** [comment]
1802 and 2a06 are already in because of the new firmware for the old miband. They are part of the standard bt sig designed uuids and are documented in the corresponding classes. So they should be removed from here as well.
--

**Comment by platinumthinker** [comment]
thanks for tips

**Comment by cpfeiffer** [comment]
@platinumthinker Do you want to update this PR or shall we do it ourselves?

**Pull request closed without merging**
