### PR TITLE
Piechart:graphic optimization pie sleep

### PR DESCRIPTION
**Pull request by albertsal**
on my galaxy s6 I noticed that the pie chart to sleep is difficult to
read because the label are above the values, I thought it was better to
use a legend and change the color of the values ...

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Thanks for working on this, however I did not merge this, because the legend would mostly be duplicated among the two charts. Both charts use the same colors, so no need to have two legends with the same colors and labels.

I did try to improve the labelling in the pie chart though, let me know if you like it, or feel free to improve it.

**Comment by albertsal** [comment]
Ok tk

**Comment by albertsal** [comment]
screenshot_20170405-081924

I am attaching a screenshot of the previous version in order to see the problem

**Comment by albertsal** [comment]
screenshot_20170405-093524


on this current version ....
how do you see the character of the values is too small to any graphics ... I suggest you zoom in all the graphic characters and maybe to use white color for the pie charts

**Comment by danielegobbetti** [comment]
Update your fork to the latest master! I see from your screenshots that you are probably not aligned with the latest changes.

Just to be clear: this is not related to the pull request content, but you should ensure you keep your fork up to date to avoid conflicts.

**Comment by albertsal** [comment]
Now I put the last update, and the situation is this

screenshot_20170405-193320
screenshot_20170405-193334
screenshot_20170405-193341

**Pull request closed without merging**
