### PR TITLE
Add Screenshots in Fastlane Directories

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds some screenshots in the corresponding fastlane directory.

They will show up on F-Droid website and in the F-Droid client at the next release you'll tag :)

Ask if you have any question 👍

### CODE REVIEW

**Comment by IzzySoft** [comment]
Could you please check the second screenshot again: is it normal that the title is shown in French while everything else is in English? Might confuse people.

(IIRC that can happen when you switch the language but do not restart the app)

**Comment by Poussinou** [comment]
@IzzySoft Ahhhhh thanks I couldn't figure out why this was still in French. I manually stopped the app and restarted it like you said 💯 

I'm on my way to add fastlane directories at least to the biggest F-Droid apps, if you want to join me? 😛

**Comment by IzzySoft** [comment]
Thanks for the fast fix – looks good to me now (so maybe @ashimokawa or @cpfeiffer want to merge it?) Sorry for not joining you in the party currently, but I've got some other parties to attend to. :+1: for you meanwhile, keep it up!

**Comment by vanous** [comment]
Thank you @Poussinou , this helped me to know where the pictures belong to. Rather then generic screenshots of settings i have now included some real data in gadgetbridge here: https://github.com/Freeyourgadget/Gadgetbridge/pull/1592

**Comment by Poussinou** [comment]
Closing in favor of #1592

**Pull request closed without merging**
