### PR TITLE
Start working on quick replies

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Does that support only one level answers? otherwise we could do:

Reply > +0436438294 > [quick, replies]

That would be an easy way to get the phone number

**Comment by ashimokawa** [comment]
We do not get any detail back from the pebble just the action id and the chosen reply id.

**Comment by roidelapluie** [comment]
this is too complex for my current knowledge, closing

**Comment by ashimokawa** [comment]
Thank you anyway, nothing in the PR was bad, it was just missing something.

Plus the real challenge is to find a _smart_ way of mapping a message id back to a phone number and a _good_ place in the code to send out the SMS.

**Comment by roidelapluie** [comment]
@ashimokawa do you plan to add this to your roadmap?

**Comment by ashimokawa** [comment]
It is on the roadmap in my head, yes ;)

**Pull request closed without merging**
