### PR TITLE
Revamp and add icons

### PR DESCRIPTION
**Pull request by xphnx**
I made some changes to the icons. Hope you like it.
- Background changed to blue because it's complementary color of orange, and seems to be secondary color of the app
- Simplied and remade icons
- Added icons for fitbit and jawbone
Of course feel free to discard some or all the changes, and request modifications.

PD: I have already received my miband, so I can do the tests that you may need, I'll be attentive to your timeline. Thanks.

### CODE REVIEW

**Comment by ashimokawa** [comment]
Wow - thanks.
Mind if I only merge the revamp commit as we do not have fitbit and jawbone support?

**Comment by xphnx** [comment]
No problem. For that reason I do 2 commits.xD

**Comment by ashimokawa** [comment]
Thanks, done. ;)

**Comment by xphnx** [comment]
Hi, I this easily might be "Painting the Bike Shed " but I think this images would look better than an icon image for the devices, considering that the entire row can be tapped, not just the icon itself and can also mislead the user about the long press.

Probably you are more interested in improve the code, so feel free to discard it ;)

ic_device_miband2
ic_device_pebble2
ic_device_pebble3
ic_device_miband2
ic_device_pebble2
ic_device_pebble3
ic_device_miband2
ic_device_pebble2
ic_device_pebble3
ic_device_miband2
ic_device_pebble2
ic_device_pebble3

**Comment by ashimokawa** [comment]
Thank you, I'll try them tomorrow.
But if we decide for this set, then I would need icons for pebble "fitness" app types also...

**Comment by xphnx** [comment]
Sure, no problem.

**Pull request closed without merging**
