### PR TITLE
incoming call and privacy

### PR DESCRIPTION
**Pull request by albertsal**
i add new function for show only call name

in string file i add
<string name="pref_call_privacy_mode_number">Hide number but display
name</string>

in array file i add
<item name="number">@string/pref_call_privacy_mode_number</item>
and
<item>@string/pref_call_privacy_mode_number</item>

in dbdeviceservice file i add a controll for
pref_call_privacy_mode_number

on hplussupport file  i change show incomming call , for first show name
and for second show the number

### CODE REVIEW

**Comment by Avamander** [comment]
Shouldn't translations be handled via other channels?

**Comment by albertsal** [comment]
I only translated my Italian language because I saw that was missing

**Comment by danielegobbetti** [comment]
Please remove the translation from this PR but please join the transifex team for italian!

Also please remove the commit related to SharedPreferences import/export. As much as I found the feature interesting this is off topic in this Pull Request.

Regarding the main topic, I'd kindly ask @jpbarraca to review commit https://github.com/Freeyourgadget/Gadgetbridge/pull/588/commits/5da99be965c7d7b537de16b0a45e153a651151d9 before we proceed merging.

**Comment by albertsal** [comment]
hi @danielegobbetti  thanks for the tips .. now I make a new request for other changes.

I'm happy if my contribution enters the release

**Comment by jpbarraca** [comment]
I have to validate that these changes are valid in HPlus devices. Probably I can do it until tuesday.

**Comment by danielegobbetti** [comment]
Thanks!

**Comment by jpbarraca** [comment]
It's ok. Works as expected.

**Comment by albertsal** [comment]
very good

**Comment by albertsal** [comment]
;)  in a few days I propose my idea to export sharedpreference

**Pull request merged**
