### PR TITLE
Auto sync feature

### PR DESCRIPTION
**Pull request by ritualz**
#1116, requested a feature which makes the application able to automatically refresh the activity data without the need to open the application. I think this might be a possible solution, where the activity data is transferred when the screen is unlocked. There might be a possibility for improvement, where the snackbar tooltip could be removed, and a period between the syncs (since this will always update, when the phone is unlocked). 

I've been using this patch for a few weeks with the MiBand2 and it seems to work without major problems.

### CODE REVIEW

**Comment by danielegobbetti** [comment]
> seems to work without major problems.

are there minor problems to report? :-)

**Comment by ritualz** [comment]
Not bugs, but the snackbar is annoying, and should be removed (in my opinion). But i could not find the function to sync the activity without it. 

screenshot_20180619-173017

**Comment by danielegobbetti** [comment]
The screenshot contains a toast, or do you mean the snackbar in controlcenter?

**Comment by ritualz** [comment]
I'm taking about the toast (not that into the whole android dev stuff). Is there a way to get rid of it?

**Comment by danielegobbetti** [comment]
I will move the toast to a notification after having merged this. Thanks!

**Comment by danielegobbetti** [comment]
please test current master, as the toast is now gone :)

**Comment by ritualz** [comment]
Yeah, the toast is gone, thanks :+1:

**Pull request merged**
