### PR TITLE
auto-export new data after fetching (csv)

### PR DESCRIPTION
**Pull request by Vebryn**
Someone got no data, this commit adds debug

### CODE REVIEW

**Comment by Vebryn** [comment]
Related to #673, no #686

**Comment by cpfeiffer** [comment]
I think this is not necessary anymore, since @ashimokawa fixed the issue with Pebbles.

**Comment by cpfeiffer** [comment]
Besides, if you log something, it is best to use an own logger for every class (see the static LOG field in many classes). This way you get all log statements automatically prefixed with the class name for easy grepping.

**Comment by Vebryn** [comment]
Understood, I'm going to review my logger. Why does travis-ci failing ? Is it my logger !?

**Comment by ashimokawa** [comment]
@Vebryn 
Travis failure was random. You can check the travis log yourself, it failed to download a dependency.

That being said you should update your branch and only have one commit in the PR, not all previously merged commits again.

Also I cleaned up your code a bit (removed tons of unused stuff you only copy and pasted as was not neccessary, renamed piechart and sleep variables to something more sane etc). Please rebase your future work on that.

And please use LOG.warn() LOG.info() and LOG.error() for logging. ;)

**Comment by Vebryn** [comment]
Hello,

I have switched from GB logging to Android logging. I also add a functionality to auto-export data into a csv file.

**Comment by cpfeiffer** [comment]
I think this PR contains too many commits -- I think we only need 64704e872e6a532d8477deffce8adef596760d29, right?

AFAICS, this is only done for Mi Bands, atm. If we want that, it should be done for all devices. I guess we should fire an event whenever activity data is being successfully provided by a device and have somone optionally (in the service?) react on that event in order to perform the export.

Additionally, I'd like to see the export in a separate class (CSVExport?), not in the SampleProvider. Also a header comment in the CSV file would be nice for people who want to understand what it means :-)

Finally, the close() of the FileWriter should be done in a finally-block ;-)

**Comment by Vebryn** [comment]
Is fetching available with other devices ? FetchActivityOperation only mentions MiBand device.

I agree with a static method in a dedicated class: CSVExport.exportToCSV. What about CSV.export ?

**Comment by danielegobbetti** [comment]
Fetching is not possible for pebbles (with stock firmware and no helper app on watch).

**Comment by Vebryn** [comment]
Export is not available when device doesn't support fetching. Actually, export is done after fetching. No fetching means no export.

**Comment by Vebryn** [comment]
According to #709, PR closed, I'm going to open a new one into a dedicated branch.

**Pull request closed without merging**
