### PR TITLE
Rtl support: Add missing Persian letters + fix bug

### PR DESCRIPTION
**Pull request by roigreenberg**
In addition to https://github.com/Freeyourgadget/Gadgetbridge/pull/1233

### CODE REVIEW

**Comment by roigreenberg** [comment]
@cpfeiffer please merge this small addition.

**Comment by yarons** [comment]
That was a really important fix, thank you for that!
I reviewed some of your translation suggestion and adjusted them to the overall localization style.

Thank you!

**Comment by roigreenberg** [comment]
Thanks.
Can you please explain what did you adjust?

**Comment by roigreenberg** [comment]
Thanks, X2!

**Pull request merged**
