### PR TITLE
Xwatch Basic Support

### PR DESCRIPTION
**Pull request by ladbsoft**
Basic support for the affordable Chinese Casio-like smart watches.

What does work:
* Activity syncing
* Multimedia control using the watch's button (one click play/pauses; double click skips to the next song/track)

What needs fixing:
* Intensity needs to be scaled down/up until a nice proportion
* Device must be set busy so the user cannot click sync again while syncing

What will be implemented next:
* Notifications
* Alarms

Will be fixing/implementing in my free time. Hope someone can make use of this :)

### CODE REVIEW

**Comment by ladbsoft** [comment]
Hi,

I have been trying to understand why the Travis CI build fails, but I couldn't. It's late in the night right now, I'll try to review it this weekend :)

**Comment by NotAFile** [comment]
Nice! However, it seems in a few files you changed the formatting/line endings such that the whole file is marked as changed. This is unfortunate as it pollutes the history. Also, I would encourage you to use more descriptive individual commit messages in the future so changes can be better understood.

Either way, let's see if the maintainers mind.

**Comment by ashimokawa** [comment]
@ladbsoft 
Wow, thanks! This is great.
However is is pretty much impossible to review the changes because you reformatted all lines in the files you touched. We use the default android studio style, if you reformat the files you changed again the diff should look much better.

About the commit messages, they are all the same, but I don't mind, I would squash this into one commit, it is only pressing a button in github, so don't worry.

**Comment by NotAFile** [comment]
re: unauthorized:

This is might be because you have 2fa enabled. It is not very well documented, but pushing over https is not allowed with 2fa on.

**Comment by cpfeiffer** [comment]
There's no UI for it, but you can append `?w=1` to the URL to ignore all whitespace changes, i.e. see this: https://github.com/Freeyourgadget/Gadgetbridge/pull/972/files?w=1

For travis, I also have no idea yet. Might be a problem on their side, or we somehow reached a limit in aapt.

In any case, nice job! :+1:

**Comment by ashimokawa** [comment]
The recent conflict comes exactly from the problem with indention :/
Shall we clean the mess up or will you @ladbsoft 
Would be too bad to have this rotting

**Comment by ladbsoft** [comment]
@ashimokawa: I'll try to redo the changes this afternoon, after work. Hopefully that will solve the problem. :)

**Comment by ladbsoft** [comment]
Hi!

I solved the indentation problems, and the branches does not have any conflicts now. Travis build still fails... "You have not accepted the license agreements of the following SDK components: [Android SDK Platform 27].". It is right, I am testing the app in an oreo device, but I didn't change the target API :/

Any advice? Thanks!

**Comment by ashimokawa** [comment]
It is not your fault. Travis is broken and we changed the target SDK.

Many thanks! Will have a look later today.

**Comment by ashimokawa** [comment]
squashed and merged, thanks!

**Pull request merged**
