### PR TITLE
Added question

### PR DESCRIPTION
**Pull request by robin13**
Where can we discuss gadgetbridge without creating noise in the issues?
Should we create a google group or something like that?

### CODE REVIEW

**Comment by serjum** [comment]
@robin13 ,  gitter.im can be useful  http://blog.gitter.im/about/

**Comment by sami10007** [comment]
@serjum Which room can be useful for Gadgetbridge in Gitter?

**Comment by serjum** [comment]
You can create a new room

**Comment by robin13** [comment]
I'd definitely prefer something more standard, persistant, searchable, not requiring another registration like email.  Google groups work well for most other projects I'm involved in.

**Comment by serjum** [comment]
@robin13 gadgetbridge already has a room on gitter (https://gitter.im/Freeyourgadget/Gadgetbridge), you'll need to sign in with your github account, no registration, no emails ...

**Comment by robin13** [comment]
So Gitter looks interesting, but it does not look very async, does not seem to allow topics / threads, and I cannot see how one could search/find all posts related to a topic historically... am I missing something?

**Comment by ashimokawa** [comment]
Thanks to the noise in the issue tracker (mostly unnecessary questions, duplicates) we disabled it, and also made the wiki read-only.

**Comment by IzzySoft** [comment]
> Thanks to the noise in the issue tracker (mostly unnecessary questions, duplicates) we disabled it, and also made the wiki read-only.

That's a big pity. For one, I've just convinced a Mi Band user to fill some gaps – and secondly, that excludes me from continue on the Pebble part as well. I hope both (issues & wiki) are only temporary measures?

As for discussions: Why not asking the XDA people for an own area? Many apps/projects have their own area there.

**Comment by ashimokawa** [comment]
Yes temporarily. I can open the wiki again as soon as I have time to monitor it (to remove crap edits)

**Comment by ashimokawa** [comment]
I have unlocked the wiki again, will see how it goes.
Issues will stay closed until the next release . We are still not ready with our big internal changes, and we have to focus on that to ensure the future of the project.

**Comment by wanderer** [comment]
@ashimokawa the issue tracker was a great reference. Even if no one from the project responds it gives space for ad-hoc discussions. This is how opensource works. Please consider reopening it and posting that you responding to anything till the next release.

**Comment by cpfeiffer** [comment]
We will release and open up everything real soon now, promised!

Sorry for the inconvenience. It was kind of a "do not disturb" mode for us so that we can fully concentrate on the db migration, with all the many details, issues and opportunities that come with it.

**Comment by ashimokawa** [comment]
@wanderer
An issue tracker is an issue tracker and not a forum. I would never have closed it if it would have been used properly.

**Comment by ashimokawa** [comment]
issue tracker reopened.

**Comment by wryk** [comment]
Why not using [contributing guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) or/and [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) github feature to inform users to not use the issue tracker to ask questions and link some external discussion service like gitter ? That could reduce unwanted noise here.

**Comment by robin13** [comment]
I'm +1 for mailing list (google groups), and -1 for gitter because gitter does not allow topics/threads and is not as universally accessible as emails are.

**Comment by IzzySoft** [comment]
@robin13 I'm -1 for google groups, as my intention when chosing GB was to get rid of that cloud stuff :) If there's anything with Github integration, that's fine with me – but especially google groups is something I h... don't like. Their web interface is a horror :)

**Comment by robin13** [comment]
@IzzySoft I'm also very much for keeping personal data personal - that's my main interest in using and working on Gadgetbridge, but I think all info around open source projects should be as accessible for all as possible: blow it out to all the clouds! :)
My gripe with gitter (and similar) is (besides lacking threads/topics) that it is not indexed like groups are: if someone else has a question which has been asked before, it will be very difficult for them to find it (and the answer).  Just taking a question I asked a while back on gitter [for](https://www.google.de/search?q=gadgetbridge+%22capturing+data+from+two+devices%22&gws_rd=cr&ei=T2_UV8GLAsG1aZbchKgE)  [example](https://duckduckgo.com/?q=gadgetbridge+%22capturing+data+from+two+devices%22&t=h_&ia=web) does not find the [correct entry](https://gitter.im/Freeyourgadget/Gadgetbridge?at=57ac407846610f173951681d).

> Their web interface is a horror :)

I wouldn't know... I never use their web interface. :)  That's the beauty of email groups: you get to look at it in your email client/web interface with your formatting and filtering rules just the way you like to with no need for giving permissions (OAuth) to some third party app, or viewing through some restrictive web interface: view it your way if it's in pine or gmail.

**Comment by IzzySoft** [comment]
I certainly agree. But what help are emails of the past for a new member of our group, if there's no way to check existing collected information? Not arguing on gripe at all :)

I recently stumbled upon a forum software integrating with Github ([Ostio](http://ost.io/)). But as not even one of their demos seemed to be working (just showing the spinning "loading" circle – maybe I had to login first?), I didn't mention it. [vanilla](https://github.com/vanilla/vanilla) seems to offer GH integration as well, but only for "Enterprise members". There might be another one that works with Github logins and offers some more integration – I'd be open for such a candidate :)

**Comment by Avamander** [comment]
What do you think about joining https://discordapp.com/channels/221364737269694464/221397928592277504 and then asking for a gadgetbridge specific room?

**Pull request closed without merging**
