### PR TITLE
Correct buildTools version in travis.yml

### PR DESCRIPTION
**Pull request by sarg**

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Thanks, I'll merge it on Sunday when I'm back home unless someone else beats me to it.

**Comment by cpfeiffer** [comment]
Hmm, apparently Travis doesn't know this version yet. Needs some research if there's anything we need to configure or if we have to wait for some updates on Travis's side.

**Comment by sarg** [comment]
Please check my PR again. I found the solution on https://github.com/travis-ci/travis-ci/issues/5036

**Comment by cpfeiffer** [comment]
Merged, thanks!

**Pull request merged**
