### PR TITLE
Added basic iTag support

### PR DESCRIPTION
**Pull request by TaaviE**
This commit should add basic "locate tag" functionality to Gadgetbridge. First step towards resolving [this issue](https://github.com/Freeyourgadget/Gadgetbridge/issues/774) This is so basic because I've got many issues to tackle before full functionality could be offered, namely:

- [ ] Support for multiple connections (lack of this is currently making link loss characteristic pretty impossible to use, https://github.com/Freeyourgadget/Gadgetbridge/issues/305 if you want more than one wearable)
- [ ] Easy way to rename devices (use of multiple trackers is rather cumbersome, for example I've got five of these tags and testing new changes is a headache when you've got "iTag", "ITAG", "iTAG" and etc. in the list :laughing:)
- [ ] Auto-discovery of characteristics and some manual exclusion wizard is needed because of two reasons:
    - [ ] Some devices have the ability to mute the beeping and just flash when instant alert is written, but not all of them, I can't think of a good way to detect this but giving the user the option would be nice (per-device)
    - [ ] Some devices advertise instant alert but actually don't beep when it's written (making locate unreliable as it might not exist in the tag)
- [ ] Easy way to set-up intents to trigger when the button on the device is pressed (with different tags)
- [ ] Live data alert support (https://github.com/Freeyourgadget/Gadgetbridge/issues/989)
- [ ] Nut* (Nut 3 mini for example) tags are much much more complicated, I haven't managed to make those beep even, the official app even contains mentions of DFU, will add support separately most likely

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Looks good so far :+1: Would be nice if you could use upper case first character for class names (`ITagCoordinator` instead of `iTagCoordinator`) as per Java naming conventions.

re renaming devices: do you mean on the db level or renaming the BT devices? If the latter, we need to make sure the device discovery based on BT name still works (not sure how persistent the name is).

re characteristics: you have all the available characteristics in the *Support class, so you could make use of them when available, or not use them otherwise. Or am I missing something?

re intent selection: yes, very much needed!

**Comment by TaaviE** [comment]
@cpfeiffer 
> Would be nice if you could use upper case first character for class names (ITagCoordinator instead of iTagCoordinator) as per Java naming conventions.

Okay, can do.

> re renaming devices: do you mean on the db level or renaming the BT devices?

DB level

> re characteristics: you have all the available characteristics in the *Support class, so you could make use of them when available, or not use them otherwise. Or am I missing something?

That's the thing, some of these modules advertise some functionality but actually lack it (for ex. tags without buttons advertise they have a button). So I don't really know how setting those devices up could work properly.

**Comment by cpfeiffer** [comment]
I see. Certain things need to be detected by hw version, fw version, appearance, ... See e.g. nodomain.freeyourgadget.gadgetbridge.service.btle.profiles.deviceinfo.DeviceInfo (deviceinfo profile: https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.device_information.xml).

So far we have custom solutions to store such additional information in the *support classes (see other DeviceInfo classes). Maybe we should make it possible to add such metadata to a GBDevice instance, like addDeviceInfo(ItemWithDetails), but a little more typed.

**Comment by ashimokawa** [comment]
@TaaviE 

Will you do the changes requested by @cpfeiffer , maybe we can then merge for 0.25.0 release (the next one)

**Comment by TaaviE** [comment]
Done. Though rest of the items on the TODOlist would have to be resolved for full support.

**Comment by ashimokawa** [comment]
@TaaviE 
Yes, totally agree. Do you still want to have this merged now?

**Comment by TaaviE** [comment]
I'm not opposed to it as it won't hurt anyone if it's there, but it doesn't have many practical uses either. It's up to you to decide.

**Comment by TaaviE** [comment]
(Takes more work to resolve conflicts than the GH issue resolver provides, does not build)

**Pull request closed without merging**
